# -*- coding: utf-8 -*-
"""inventoryapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12D0D7tfKU8EPEe1bKOmf_bRDkDOSjkaq
"""



import streamlit as st
import pandas as pd

st.set_page_config(page_title="Inventory Management System", layout="wide")

st.title("📦 Inventory Management System")

# Initialize inventory in session state
if "inventory" not in st.session_state:
    st.session_state.inventory = pd.DataFrame(
        columns=["Product ID", "Product Name", "Category", "Price", "Quantity"]
    )

# Sidebar menu
menu = st.sidebar.selectbox(
    "Menu",
    ["Add Product", "View Inventory", "Update Stock", "Delete Product", "Low Stock Alert"]
)

# -----------------------------
# ADD PRODUCT
# -----------------------------
if menu == "Add Product":
    st.header("➕ Add New Product")

    product_id = st.text_input("Product ID")
    product_name = st.text_input("Product Name")
    category = st.text_input("Category")
    price = st.number_input("Price", min_value=0.0)
    quantity = st.number_input("Quantity", min_value=0)

    if st.button("Add Product"):
        if product_id and product_name:
            new_data = pd.DataFrame(
                [[product_id, product_name, category, price, quantity]],
                columns=["Product ID", "Product Name", "Category", "Price", "Quantity"]
            )
            st.session_state.inventory = pd.concat(
                [st.session_state.inventory, new_data],
                ignore_index=True
            )
            st.success("Product Added Successfully!")
        else:
            st.error("Please fill all required fields.")

# -----------------------------
# VIEW INVENTORY
# -----------------------------
elif menu == "View Inventory":
    st.header("📋 Current Inventory")

    if not st.session_state.inventory.empty:
        st.dataframe(st.session_state.inventory)
    else:
        st.warning("Inventory is empty.")

# -----------------------------
# UPDATE STOCK
# -----------------------------
elif menu == "Update Stock":
    st.header("🔄 Update Product Quantity")

    if not st.session_state.inventory.empty:
        product_list = st.session_state.inventory["Product ID"].tolist()
        selected_product = st.selectbox("Select Product ID", product_list)

        new_quantity = st.number_input("Enter New Quantity", min_value=0)

        if st.button("Update"):
            st.session_state.inventory.loc[
                st.session_state.inventory["Product ID"] == selected_product,
                "Quantity"
            ] = new_quantity

            st.success("Stock Updated Successfully!")
    else:
        st.warning("Inventory is empty.")

# -----------------------------
# DELETE PRODUCT
# -----------------------------
elif menu == "Delete Product":
    st.header("❌ Delete Product")

    if not st.session_state.inventory.empty:
        product_list = st.session_state.inventory["Product ID"].tolist()
        selected_product = st.selectbox("Select Product ID to Delete", product_list)

        if st.button("Delete"):
            st.session_state.inventory = st.session_state.inventory[
                st.session_state.inventory["Product ID"] != selected_product
            ]
            st.success("Product Deleted Successfully!")
    else:
        st.warning("Inventory is empty.")

# -----------------------------
# LOW STOCK ALERT
# -----------------------------
elif menu == "Low Stock Alert":
    st.header("⚠ Low Stock Products (Quantity < 5)")

    if not st.session_state.inventory.empty:
        low_stock = st.session_state.inventory[
            st.session_state.inventory["Quantity"] < 5
        ]

        if not low_stock.empty:
            st.dataframe(low_stock)
        else:
            st.success("No low stock products.")
    else:
        st.warning("Inventory is empty.")